---
title: "Maaslin runs"
author: "Joonatan Palmu"
date: "`r format(Sys.time(), '%d.%m.%Y')`"
output: html_document
---
	
```{r setup, include=FALSE}
knitr::opts_chunk$set(include = TRUE, xecho = TRUE, message = FALSE, results='asis',
                      cache=FALSE, warning=FALSE)
knitr::opts_chunk$set(cache.path = 'cache/', output.dir="cache/",
                      file.path = 'cache/', fig.path = 'cache/')

options(max.print=100)

dir.create("rds/", showWarnings = FALSE)
dir.create("session/", showWarnings = FALSE)
```

# Command line arguments

Calculations ran at

```{r Command line arguments}
now <- format(Sys.time(), '%Y%m%d-%H%M%S')

if (exists("args")) {
    if ("time" %in% names(args)) now <- args$time
    
    if("clean" %in% names(args)) {
        unlink("rds", recursive=TRUE)
        unlink("cache", recursive=TRUE)
    }
    if ("tags" %in% names(args)) 
        rtags('~/phd/research/articletwo/', recursive = FALSE, pattern = '\\.[RrSs](rw|md)?$',
              ofile = '~/phd/research/articletwo/TAGS', verbose = TRUE, append = FALSE)
    if ("loadlast" %in% names(args) )
        load(paste0("session/", sort(list.files("session"), decreasing = TRUE)[1]))
    if ("subset" %in% names(args))
        subset.run <- as.numeric(args$subset)
}

#packrat::opts$ignored.packages
```


# Importing libraries:

```{r libraries, cache = FALSE}
library(dplyr)
library(tibble)
library(phyloseq)
library(nortest)
library(microbiome)
library(knitr)
library(tidyr)
library(vegan)
library(reshape)
library(parallel)
library(officer)
library(flextable)
library(xtable)
library(rvg)
library(tableone)
library(scales)
library(ggplot2)
library(gridExtra)
library(png)
library(pander)
library(ggpubr)
library(broom)
library(ggfortify)
library(RColorBrewer)
library(gvlma)
library(purrr)
library(pwr)
```

### RR biome functions

<details>
  <summary>Open/Close</summary>
  
```{r RR biome functions, code=readLines("articletwo-rrbiome.R")}
source("articletwo-rrbiome.R")
```

</details>

```{r data}
pseq.genus <- import_filter_data("data/phfinrisk_centrifuge_genus_d50k_2019-06-02.rds")
pseq.genus.core <- microbiome::transform(pseq.genus, "compositional") %>%
    core(detection = 0.0001, prevalence = 0.01)
```


## Variables

```{r my variables}
var.BP <- c("MAP", "SYSTM", "DIASM", "PULSEPRESSURE", "HYPERTENSION")
var.CL.min <- c("BL_AGE", "SEX")
var.CL.add <- c("SEX", "BMI", "CURR_SMOKE", "Q57X", "PREVAL_DIAB",
            "BL_USE_RX_C03","BL_USE_RX_C07", "BL_USE_RX_C08", "BL_USE_RX_C09")
```

```{r var combinations}
var.CL.list <- seq(length(var.CL.add)) %>% as.list
names(var.CL.list) <- var.CL.add
var.CL.comb <- lapply(var.CL.list, function(x) unique(c(var.CL.min, var.CL.add[1:x])))
var.CL.comb3rd <- lapply(var.CL.list, function(x) unique(c(var.CL.min, var.CL.add[x])))
```

```{r maaslin runs, results = 'hide', eval  = FALSE} 
ret <- mclapply(var.CL.comb, function(x)
    maaslinwrapper(pseq = pseq.genus.core,
                   looped = var.BP,
                   forced = x,
                   taxa = taxa(pseq.genus.core),
                   tempstr = sprintf("%%s/maaslinruns/combinations/single_%s", paste0(x, collapse = "_"))),
    mc.cores = length(var.CL.comb))
```

```{r adding third, results = 'hide', eval = FALSE}
ret3rd <- mclapply(var.CL.comb3rd, function(x)
    maaslinwrapper(pseq = pseq.genus.core,
                   looped = var.BP,
                   forced = x,
                   taxa = taxa(pseq.genus.core),
                   tempstr = sprintf("%%s/maaslinruns/combinations/all3rd_%s", paste0(x, collapse = "_"))),
    mc.cores = length(var.CL.comb3rd))

```

```{r read combinations}
ret <- lapply(var.CL.comb, function(x) {
    file <- sprintf("/homes/jpalmu/maaslinruns/combinations/single_%s/maaslin/maaslin.txt",
                    paste0(x, collapse = "_"))
    read.table(file, header=TRUE, sep='\t') %>% as.data.frame
    })
```

```{r combine results}
ret.comb <- map_df(ret, ~as.data.frame(.x), .id="id")

ret.comb %>%
    dplyr::filter(Q.value < 0.05) %>%
    group_by(id) %>%
    summarize(n = n(), model = paste0(var.CL.comb[[id[1]]], collapse = "+")) %>%
    arrange(model) %>%
    kable
```


```{r read combinations 3rd}
ret3rd <- lapply(var.CL.comb3rd, function(x) {
    file <- sprintf("/homes/jpalmu/maaslinruns/combinations/all3rd_%s/maaslin/maaslin.txt",
                    paste0(x, collapse = "_"))
    read.table(file, header=TRUE, sep='\t') %>% as.data.frame
    })
```

```{r combine results 3rd}
ret3rd.comb <- map_df(ret3rd, ~as.data.frame(.x), .id="id")

ret3rd.comb %>%
    dplyr::filter(Q.value < 0.05) %>%
    group_by(id) %>%
    summarize(n = n(), model = paste0(var.CL.comb3rd[[id[1]]], collapse = "+")) %>%
    arrange(n) %>%
    kable
```
